version: "3.9"
services:
  database:
    restart: always
    image: postgres:latest
    container_name: database
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"

  nats-streaming:
    image: nats-streaming:0.24.6
    container_name: nats_streaming
    ports:
      - "4222:4222"
  
  order-service:
    build: ./
    command: ./wait-for-postgres.sh database ./order-service
    container_name: order_service
    depends_on:
      - database
      - nats-streaming
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  dbdata: